In [2]:
#Time performance python list vs numpy array
import time
import numpy as np
size = 10_000_000
start = time.time()
py_list = list(range(size))
sq_list = [i ** 2 for i in py_list]
end = time.time()
print(f"Time taken for python list to execute : {end - start} seconds")

start = time.time()
numpy_arr = np.array(py_list)
sq_arr = numpy_arr ** 2
end = time.time()
print(f"Time taken for numpy arr to execute : {end - start} seconds")

Time taken for python list to execute : 1.1077852249145508 seconds
Time taken for numpy arr to execute : 0.4665343761444092 seconds


In [4]:
#Memory usage
import sys
print(f"size of python list : {sys.getsizeof(py_list) * len(sq_list)}")
print(f"size of numpy array : {sq_arr.nbytes}")

size of python list : 800000560000000
size of numpy array : 80000000


In [9]:
#Creating numpy arrays from lists
arr2 = np.array([1, 2, 3, 4, 5])
print(f"{arr2} TYPE : {type(arr2)} DTYPE : {arr2.dtype} SHAPE : {arr2.shape}")
arr2 = np.array([1, 2, 3, 4, 5,'pixel'])
print(f"{arr2} TYPE : {type(arr2)} DTYPE : {arr2.dtype} SHAPE : {arr2.shape}")
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"{arr2D} TYPE : {type(arr2D)} DTYPE : {arr2D.dtype} SHAPE : {arr2D.shape}")

[1 2 3 4 5] TYPE : <class 'numpy.ndarray'> DTYPE : int64 SHAPE : (5,)
['1' '2' '3' '4' '5' 'pixel'] TYPE : <class 'numpy.ndarray'> DTYPE : <U21 SHAPE : (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] TYPE : <class 'numpy.ndarray'> DTYPE : int64 SHAPE : (3, 3)


In [24]:
#Create
arr2 = np.zeros((5), dtype="int64") #default dtype = float      #prefill
print(f"{arr2} TYPE : {type(arr2)} DTYPE : {arr2.dtype} SHAPE : {arr2.shape}")

arr2 = np.ones((5)) #prefill with ones
print(f"{arr2} TYPE : {type(arr2)} DTYPE : {arr2.dtype} SHAPE : {arr2.shape}")

arr2 = np.full((5,3),True) #prefill with some val
print(f"{arr2} TYPE : {type(arr2)} DTYPE : {arr2.dtype} SHAPE : {arr2.shape}")

arr2 = np.eye(3) #identity matrix
print(f"{arr2} TYPE : {type(arr2)} DTYPE : {arr2.dtype} SHAPE : {arr2.shape}")

arr2 = np.arange(1,11) #range elements
print(f"{arr2} TYPE : {type(arr2)} DTYPE : {arr2.dtype} SHAPE : {arr2.shape}")

arr2 = np.linspace(1,100, 4) # evenly spaced elements
print(f"{arr2} TYPE : {type(arr2)} DTYPE : {arr2.dtype} SHAPE : {arr2.shape}")


[0 0 0 0 0] TYPE : <class 'numpy.ndarray'> DTYPE : int64 SHAPE : (5,)
[1. 1. 1. 1. 1.] TYPE : <class 'numpy.ndarray'> DTYPE : float64 SHAPE : (5,)
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]] TYPE : <class 'numpy.ndarray'> DTYPE : bool SHAPE : (5, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] TYPE : <class 'numpy.ndarray'> DTYPE : float64 SHAPE : (3, 3)
[ 1  2  3  4  5  6  7  8  9 10] TYPE : <class 'numpy.ndarray'> DTYPE : int64 SHAPE : (10,)
[  1.   50.5 100. ] TYPE : <class 'numpy.ndarray'> DTYPE : float64 SHAPE : (3,)


In [30]:
#Properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape) # dimensions m x n
print(arr.size) # number of elements
print(arr.dtype)  
print(arr.ndim) 
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [35]:
#Operations on arrays
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)
reshaped_arr = arr.reshape((3, 2))
print(reshaped_arr,reshaped_arr.shape)

flattened_arr = arr.flatten() #2D -> 1D Array
print(flattened_arr,flattened_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [42]:
#Indexing
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0][2]) # 3
#Fancy Indexing
arr = np.array([1,2,3,4,5,6])
idx = [1,0,4]
print(arr[idx])
print(arr[arr > 3])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

3
[2 1 5]
[4 5 6]
[2 4 6]
[1 3 5]
[2 3 4]


In [44]:
#Slicing
arr = np.array([1,2,3,4,5,6])
print(arr[1:4]) #[start, end, step]
print(arr[:4])
print(arr[1:])
print(arr[::])
print(arr[::-1])

[2 3 4]
[1 2 3 4]
[2 3 4 5 6]
[1 2 3 4 5 6]
[6 5 4 3 2 1]


In [50]:
#Copy in list VS view in array
py_list = [1,2,3,4,5,6]
sub_list = py_list[1:3]
print(sub_list)
sub_list[0] = 200
print(sub_list)
print(py_list)
# [2, 3] A new copy is created from main list i.e., changing the element in sublist doesnt effect the original list
# [200, 3] 
# [1, 2, 3, 4, 5, 6]

arr = np.array([1,2,3,4,5,6])
sub_arr = arr[1:3]
# sub_arr = arr[1:3].copy() #A new copy is created rather than creating a viewx
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)

# [2 3] # A view is created for subarray so when a element in sub array is modified the changes are also reflected to the original np array.To avoid this use .copy() function
# [200   3]
# [  1 200   3   4   5   6]


[2, 3]
[200, 3]
[1, 2, 3, 4, 5, 6]
[2 3]
[200   3]
[1 2 3 4 5 6]


In [51]:
#Common Data Types
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1.0, 2.0, 3.0])
arr3 = np.array(["hello", "world", "prime", "ai/ml"])

print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

print(arr.nbytes)        # 5 elements * 8 bytes each => 40

new_arr = arr.astype("float64")
print(new_arr, new_arr.dtype)

new_arr = np.array([1, 2, 3, 4, 5], dtype="float64")
print(new_arr, new_arr.dtype)


# Complex Numbers
arr1 = np.array([2 + 3j])
arr2 = np.array([5 + 8j])
print(arr1, arr1.dtype)
print(arr1 + arr2)
print(arr2 - arr1)

# Objects
arr = np.array(["hello", {1, 2, 3}, 3.14])
print(arr, arr.dtype)


int64
float64
<U5
40
[1. 2. 3. 4. 5.] float64
[1. 2. 3. 4. 5.] float64
[2.+3.j] complex128
[7.+11.j]
[3.+5.j]
['hello' {1, 2, 3} 3.14] object


In [55]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.sum())
sum_of_columns = np.sum(arr, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr, axis = 1)
print(sum_of_rows)

print(arr[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


# 3D Arrays

In [60]:
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D, arr3D.shape)

#Indexing
print(arr3D[1, 1, 0])

#Slicing
print(arr3D[:,0:1,:]) # To slice first row of all 2D arrays of a 3D array
#[depth:(row start : row end):(col start:col end)]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[[1 2]]

 [[7 8]]]


# Vectorization

In [61]:
arr = np.array([1,2,3,4,5])
arr1 = np.array([6,7,8,9,10])
print(arr ** 2)
print(arr + arr1)

[ 1  4  9 16 25]
[ 7  9 11 13 15]


# Broadcast
Broadcasting works on array only if the dimensions of two arrays are equal or one of them is 1    
Accepted:   
2x3 2x3   
1x5 3x5   
Rejected:   
2x4 4x2    
2x3 4x3   

In [62]:
arr1 = np.array([1,2,3,4,5])
arr2D1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr1 + arr2D1)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


# Normalization

In [66]:
arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std = np.std(arr)
print(mean)
print(std)

normalized_arr = (arr - mean) / std
print(normalized_arr)

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


# Mathematical functions

In [79]:
arr = np.array([1,2,3,4,5])

#Aggregate
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr)) 

#Mathematical
print(np.mean(arr)) 
print(np.median(arr)) 
print(np.std(arr)) 
print(np.var(arr)) 

# power functions
print(np.pow(arr,3)) 
print(np.square(arr)) 
print(np.sqrt(arr)) 

#log
print(np.log(arr)) #log arr to the base e 
print(np.log10(arr)) 
print(np.log2(arr)) 
print(np.exp(arr)) 

#Rounding

print(np.round(3.14)) #3.0
print(np.round(3.94)) #4.0
print(np.round(3.50)) #4.0
print(np.round(3.49)) #3.0
'''round-> .0 to 0.49 down value
            0.50 to 0.99 up value
'''
print(np.ceil(3.1)) #4.0
print(np.floor(3.94)) #3.0
print(np.trunc(3.94)) #3.0


arr = np.array([1,2,3,4,5,5,1,3,6,-3,-9])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))







15
120
1
5
0
4
3.0
3.0
1.4142135623730951
2.0
[  1   8  27  64 125]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
3.0
4.0
4.0
3.0
4.0
3.0
3.0
[-9 -3  1  2  3  4  5  6]
[-9 -3  1  1  2  3  3  4  5  5  6]
[1 2 3 4 5 5 1 3 6 3 9]
